# Site settings
title: Grégory Joseph, Software person
# email: your-email@domain.com
description: "Grégory Joseph, Software person"
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://incongru.net

#twitter_username: hpesojg
bitbucket_username: hpesojg
github_username: gjoseph
linkedin_username: hpesojg

# Build settings
markdown: kramdown
#markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

exclude:
  - bin/